### ISSUE TITLE
CREAR INTERFAZ PARA LA PRESENTACIÓN (6/6/24)

### ISSUE THREAD

**Issue by lopezleyre** [Adalab/proyecto-da-promo-b-pt-modulo-1-team-3#12]
Para la presentación tenemos que seguir los pasos y crear una interfaz (y diseñarla)

* * Hay que importar Tkinter en python para hacer la demo de la presentación. (Aquí un videotutorial para usar Tkinter: 
[https://www.youtube.com/watch?v=jwA1Efuq48Q])

* Mirar jupyter notebook de ejemplo de interfaz que nos ha pasado Sara.

**Comment by lopezleyre** [comment]
tkinter

- Mirar jupyter notebook de ejemplo de interfaz que nos ha pasado Sara.

**Comment by VESUVERDUGO** [comment]
Aquí un videotutorial para usar Tkinter: [https://www.youtube.com/watch?v=jwA1Efuq48Q](url)

**Comment by lopezleyre** [comment]
`import tkinter as tk
from tkinter import ttk

# Function to update the label with a greeting
def greet():
    greeting_label.config(text="Hello, Tkinter!")

# Create the main window
root = tk.Tk()
root.title("Simple Greeting")

# Create and place the button
greet_button = ttk.Button(root, text="Greet", command=greet)
greet_button.pack(pady=10)

# Create and place the label
greeting_label = ttk.Label(root, text="")
greeting_label.pack(pady=10)

# Run the application
root.mainloop()`

**Comment by lopezleyre** [comment]
> Hay que importar Tkinter en python para hacer la demo de la presentación. (Aquí un videotutorial para usar Tkinter: [https://www.youtube.com/watch?v=jwA1Efuq48Q])
> 
> Mirar jupyter notebook de ejemplo de interfaz que nos ha pasado Sara.
